# Generated by Django 3.2.9 on 2021-11-17 10:54

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20211116_1439'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='variation',
            managers=[
                ('variations', django.db.models.manager.Manager()),
            ],
        ),
    ]
