# Generated by Django 4.0 on 2021-12-13 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_productgallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='productgallery',
            name='product',
            field=models.ForeignKey(default='64f471ed-f030-43ba-9075-312716bb6766', on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='store.product'),
            preserve_default=False,
        ),
    ]
