# Generated by Django 4.0 on 2021-12-13 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_productgallery_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productgallery',
            options={'verbose_name': 'gallery', 'verbose_name_plural': 'galleries'},
        ),
        migrations.AlterField(
            model_name='productgallery',
            name='image',
            field=models.ImageField(upload_to='gallery'),
        ),
        migrations.AlterField(
            model_name='productgallery',
            name='thumb',
            field=models.ImageField(blank=True, null=True, upload_to='thumbs'),
        ),
    ]
