# Generated by Django 4.0 on 2021-12-13 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_productgallery_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productgallery',
            name='image',
            field=models.ImageField(upload_to='products/gallery'),
        ),
        migrations.AlterField(
            model_name='productgallery',
            name='thumb',
            field=models.ImageField(blank=True, null=True, upload_to='products/gallery/thumbs'),
        ),
    ]
