# Generated by Django 4.0 on 2021-12-13 16:32

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_productgallery_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productgallery',
            name='thumb',
        ),
        migrations.AlterField(
            model_name='productgallery',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(upload_to='products/gallery'),
        ),
    ]
