# Generated by Django 4.0 on 2021-12-20 06:30

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_remove_productgallery_thumb_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='products/category'),
        ),
    ]
