# Generated by Django 3.2.9 on 2021-11-22 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='cart_id',
            field=models.CharField(max_length=100),
        ),
    ]
