# Generated by Django 3.2.9 on 2021-11-23 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_auto_20211123_0712'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='item_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
