# Generated by Django 3.2.9 on 2021-11-23 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0005_alter_cartitem_variation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='item_id',
        ),
        migrations.AlterField(
            model_name='itemvariation',
            name='variation_id',
            field=models.CharField(max_length=100),
        ),
    ]
