# Generated by Django 3.2.9 on 2021-11-27 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='grand_total',
            field=models.DecimalField(decimal_places=2, default=34.6, max_digits=20),
            preserve_default=False,
        ),
    ]
