# Generated by Django 3.2.9 on 2021-11-28 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderdetail_grand_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='product_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
