# Generated by Django 4.0 on 2022-01-04 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orderproduct_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('out for delivery', 'Out for delivery'), ('delivered', 'Delivered')], default='pending', max_length=20),
        ),
    ]
